name: PkillX
version: '1.0'
summary: pkillx cli now
description: |
  Command line interface for Hackers who love football
  
base: core22

grade: stable
confinement: strict

apps:
  footie:
    command: bin/pkillx
    plugs: [network]

parts:
  footie:
    plugin: nodejs
    source: .

